In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("bow5000.csv")

In [3]:
df.head()
df.shape
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Columns: 5002 entries, Unnamed: 0 to petyr
dtypes: int64(5000), object(2)
memory usage: 5.6+ MB

Unnamed: 0    0
category_     0
the           0
and           0
to            0
             ..
rowan's       0
curry         0
enzian        0
ellie         0
petyr         0
Length: 5002, dtype: int64

In [4]:
df = df.drop_duplicates()

In [5]:
df = df.dropna()

In [9]:
df.columns = df.columns.str.strip().str.lower()

In [13]:
def remove_outliers_iqr(dataframe, column):
    if column not in dataframe.columns:
        raise ValueError(f"Column '{column}' not found. Available columns: {list(dataframe.columns)}")
    
    Q1 = dataframe[column].quantile(0.25)
    Q3 = dataframe[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return dataframe[(dataframe[column] >= lower) & 
                     (dataframe[column] <= upper)]

In [14]:
df.describe()

,the,and,to,a,of,i,he,in,was,it,...,slothrop's,katherine,malloy,lightner,mayfairs,rowan's,curry,enzian,ellie,petyr
count,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,...,147.000000,147.000000,147.000000,147.000000,147.00000,147.000000,147.000000,147.000000,147.000000,147.000000
mean,6986.809524,3629.122449,3041.272109,2990.925170,2647.727891,1807.795918,2169.904762,1932.755102,2000.183673,1732.272109,...,1.061224,1.027211,1.020408,1.217687,1.22449,0.959184,1.027211,0.897959,5.183673,1.176871
std,4465.435505,2386.352751,1890.689573,1784.245599,1818.402270,1454.840046,1523.509271,1251.461220,1379.278603,1215.367251,...,12.866663,7.790006,11.478670,12.785650,13.28806,8.388575,8.176097,10.887177,36.638931,14.268800
min,491.000000,304.000000,208.000000,301.000000,202.000000,130.000000,151.000000,174.000000,166.000000,106.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4113.000000,2094.000000,1814.000000,1865.500000,1488.500000,879.000000,1089.500000,1140.500000,1123.500000,915.500000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,6147.000000,3084.000000,2785.000000,2645.000000,2144.000000,1390.000000,1909.000000,1688.000000,1631.000000,1442.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,8835.000000,4612.500000,3711.000000,3724.000000,3232.000000,2353.000000,2877.000000,2412.000000,2567.500000,2186.500000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
max,25633.000000,15874.000000,12024.000000,11175.000000,9857.000000,8868.000000,9731.000000,7192.000000,8014.000000,7305.000000,...,156.000000,85.000000,139.000000,153.000000,160.00000,90.000000,93.000000,132.000000,404.000000,173.000000

In [16]:
df.corr(numeric_only=True)

,the,and,to,a,of,i,he,in,was,it,...,slothrop's,katherine,malloy,lightner,mayfairs,rowan's,curry,enzian,ellie,petyr
the,1.000000,0.952482,0.960650,0.962585,0.967478,0.453755,0.865776,0.979648,0.881053,0.915862,...,0.231220,0.380802,0.234451,0.352184,0.351729,0.336772,0.351819,0.231220,0.170853,0.346762
and,0.952482,1.000000,0.931404,0.927536,0.937355,0.495402,0.854450,0.943404,0.881198,0.912594,...,0.144448,0.432869,0.175425,0.436040,0.434632,0.422501,0.437090,0.144448,0.218329,0.426114
to,0.960650,0.931404,1.000000,0.945016,0.944907,0.551864,0.838977,0.960940,0.895663,0.907541,...,0.207433,0.439992,0.252686,0.403866,0.402528,0.391630,0.404487,0.207433,0.189892,0.394543
a,0.962585,0.927536,0.945016,1.000000,0.960087,0.488123,0.858744,0.970640,0.871056,0.911613,...,0.239419,0.239755,0.206691,0.207834,0.208755,0.191036,0.206455,0.239419,0.131372,0.209166
of,0.967478,0.937355,0.944907,0.960087,1.000000,0.449766,0.844282,0.979840,0.860737,0.919222,...,0.304118,0.360908,0.155556,0.336632,0.335424,0.328005,0.339333,0.304118,0.168377,0.328505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rowan's,0.336772,0.422501,0.391630,0.191036,0.328005,0.301743,0.249078,0.330062,0.312928,0.325319,...,-0.009496,0.786650,-0.010234,0.948101,0.933210,1.000000,0.989178,-0.009496,0.318792,0.881468
curry,0.351819,0.437090,0.404487,0.206455,0.339333,0.319993,0.258411,0.348086,0.327102,0.338098,...,-0.010433,0.833625,-0.011172,0.979870,0.970559,0.989178,1.000000,-0.010433,0.341759,0.934155
enzian,0.231220,0.144448,0.207433,0.239419,0.304118,-0.027102,0.055767,0.302340,-0.029995,0.095026,...,1.000000,-0.010950,-0.007382,-0.007909,-0.007652,-0.009496,-0.010433,1.000000,-0.011749,-0.006849
ellie,0.170853,0.218329,0.189892,0.131372,0.168377,0.163253,0.185286,0.176443,0.206861,0.210382,...,-0.011749,0.320253,-0.012533,0.358542,0.361091,0.318792,0.341759,-0.011749,1.000000,0.364496
petyr,0.346762,0.426114,0.394543,0.209166,0.328505,0.314356,0.260118,0.348989,0.328062,0.328844,...,-0.006849,0.895172,-0.007382,0.985835,0.992265,0.881468,0.934155,-0.006849,0.364496,1.000000

In [18]:
df.to_csv("bow5000_cleaned.csv", index=False)